services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: Creda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 35218889
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: Creda
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 35218889
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  predict-service:
    build:
      context: ./predict_service
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  db_data:
  redis_data:
